curl -o source/JGI/DNA/Chlpad1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Chlpad1/download/Chlpad1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Chlpad1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Chlpad1/download/Chlpad1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Chlpad1.gff3.gz 'https://genome.jgi.doe.gov/portal/Chlpad1/download/Chlpad1_GeneCatalog_20160815.gff3.gz' -b cookies
curl -o source/JGI/CDS/Chlpad1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Chlpad1/download/Chlpad1_GeneCatalog_CDS_20160815.fasta.gz' -b cookies
curl -o source/JGI/DNA/Absrep1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Absrep1/download/Absrep1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Absrep1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Absrep1/download/Absrep1_MitochondrionScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Absrep1.gff3.gz 'https://genome.jgi.doe.gov/portal/Absrep1/download/Absrep1_GeneCatalog_20160129.gff3.gz' -b cookies
curl -o source/JGI/CDS/Absrep1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Absrep1/download/Absrep1_GeneCatalog_CDS_20160129.fasta.gz' -b cookies
curl -o source/JGI/DNA/Amyrou1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Amyrou1/download/Amyrou1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Amyrou1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Amyrou1/download/Amyrou1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Amyrou1.gff3.gz 'https://genome.jgi.doe.gov/portal/Amyrou1/download/Amyrou1_GeneCatalog_20181016.gff3.gz' -b cookies
curl -o source/JGI/CDS/Amyrou1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Amyrou1/download/Amyrou1_GeneCatalog_CDS_20181016.fasta.gz' -b cookies
curl -o source/JGI/DNA/Bacci1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Bacci1/download/Bacci1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Bacci1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Bacci1/download/Bacci1_MitochondrionScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Bacci1.gff3.gz 'https://genome.jgi.doe.gov/portal/Bacci1/download/Bacci1.filtered_proteins.FilteredModels1.gff3.gz' -b cookies
curl -o source/JGI/CDS/Bacci1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Bacci1/download/Bacci1_GeneCatalog_CDS_20130730.fasta.gz' -b cookies
curl -o source/JGI/DNA/Basme2finSC.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Basme2finSC/download/Basme2finSC_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Basme2finSC.gff3.gz 'https://genome.jgi.doe.gov/portal/Basme2finSC/download/Basme2finSC_GeneCatalog_2015_06_30_09_37_deflines.gff3.gz' -b cookies
curl -o source/JGI/CDS/Basme2finSC.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Basme2finSC/download/Basme2finSC_GeneCatalog_CDS_20150701.fasta.gz' -b cookies
curl -o source/JGI/DNA/Benpoi1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Benpoi1/download/Benpoi1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Benpoi1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Benpoi1/download/Benpoi1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Benpoi1.gff3.gz 'https://genome.jgi.doe.gov/portal/Benpoi1/download/Benpoi1_GeneCatalog_20180911.gff3.gz' -b cookies
curl -o source/JGI/CDS/Benpoi1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Benpoi1/download/Benpoi1_GeneCatalog_CDS_20180911.fasta.gz' -b cookies
curl -o source/JGI/DNA/Blatri_F921_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Blatri_F921_1/download/Blatri_F921_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Blatri_F921_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Blatri_F921_1/download/Blatri_F921_1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Blatri_F921_1.gff3.gz 'https://genome.jgi.doe.gov/portal/Blatri_F921_1/download/Blatri_F921_1_GeneCatalog_20180606.gff3.gz' -b cookies
curl -o source/JGI/CDS/Blatri_F921_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Blatri_F921_1/download/Blatri_F921_1_GeneCatalog_CDS_20180606.fasta.gz' -b cookies
curl -o source/JGI/DNA/Blatri_F986_2.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Blatri_F986_2/download/Blatri_F986_2_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Blatri_F986_2.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Blatri_F986_2/download/Blatri_F986_2_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Blatri_F986_2.gff3.gz 'https://genome.jgi.doe.gov/portal/Blatri_F986_2/download/Blatri_F986_2_GeneCatalog_20180606.gff3.gz' -b cookies
curl -o source/JGI/CDS/Blatri_F986_2.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Blatri_F986_2/download/Blatri_F986_2_GeneCatalog_CDS_20180606.fasta.gz' -b cookies
curl -o source/JGI/DNA/Blatri1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Blatri1/download/Blatri1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Blatri1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Blatri1/download/Blatri1_MitochondrionScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Blatri1.gff3.gz 'https://genome.jgi.doe.gov/portal/Blatri1/download/Blatri1_GeneCatalog_20160404.gff3.gz' -b cookies
curl -o source/JGI/CDS/Blatri1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Blatri1/download/Blatri1_GeneCatalog_CDS_20160404.fasta.gz' -b cookies
curl -o source/JGI/DNA/Chocucu1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Chocucu1/download/Chocucu1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Chocucu1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Chocucu1/download/Chocucu1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Chocucu1.gff3.gz 'https://genome.jgi.doe.gov/portal/Chocucu1/download/Chocucu1_GeneCatalog_20180614.gff3.gz' -b cookies
curl -o source/JGI/CDS/Chocucu1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Chocucu1/download/Chocucu1_GeneCatalog_CDS_20180614.fasta.gz' -b cookies
curl -o source/JGI/DNA/Cirumb1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Cirumb1/download/Cirumb1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Cirumb1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Cirumb1/download/Cirumb1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Cirumb1.gff3.gz 'https://genome.jgi.doe.gov/portal/Cirumb1/download/Cirumb1_GeneCatalog_20170119.gff3.gz' -b cookies
curl -o source/JGI/CDS/Cirumb1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Cirumb1/download/Cirumb1_GeneCatalog_CDS_20170119.fasta.gz' -b cookies
curl -o source/JGI/DNA/Coemoj1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Coemoj1/download/Coemoj1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Coemoj1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Coemoj1/download/Coemoj1_MitochondrionScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Coemoj1.gff3.gz 'https://genome.jgi.doe.gov/portal/Coemoj1/download/Coemoj1_GeneCatalog_20180326.gff3.gz' -b cookies
curl -o source/JGI/CDS/Coemoj1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Coemoj1/download/Coemoj1_GeneCatalog_CDS_20180326.fasta.gz' -b cookies
curl -o source/JGI/DNA/Coere1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Coere1/download/Coere1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Coere1.gff3.gz 'https://genome.jgi.doe.gov/portal/Coere1/download/Coere1.filtered_proteins.FilteredModels1.gff3.gz' -b cookies
curl -o source/JGI/CDS/Coere1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Coere1/download/Coere1_GeneCatalog_CDS_20110909.fasta.gz' -b cookies
curl -o source/JGI/DNA/Coespi1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Coespi1/download/Coespi1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Coespi1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Coespi1/download/Coespi1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Coespi1.gff3.gz 'https://genome.jgi.doe.gov/portal/Coespi1/download/Coespi1_GeneCatalog_20170411.gff3.gz' -b cookies
curl -o source/JGI/CDS/Coespi1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Coespi1/download/Coespi1_GeneCatalog_CDS_20170411.fasta.gz' -b cookies
curl -o source/JGI/DNA/Cokrec1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Cokrec1/download/Cokrec1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Cokrec1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Cokrec1/download/Cokrec1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Cokrec1.gff3.gz 'https://genome.jgi.doe.gov/portal/Cokrec1/download/Cokrec1_GeneCatalog_20170123.gff3.gz' -b cookies
curl -o source/JGI/CDS/Cokrec1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Cokrec1/download/Cokrec1_GeneCatalog_CDS_20170123.fasta.gz' -b cookies
curl -o source/JGI/DNA/Conco1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Conco1/download/Conco1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Conco1.gff3.gz 'https://genome.jgi.doe.gov/portal/Conco1/download/Conco1.filtered_proteins.FilteredModels1.gff3.gz' -b cookies
curl -o source/JGI/CDS/Conco1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Conco1/download/Conco1_GeneCatalog_CDS_20120213.fasta.gz' -b cookies
curl -o source/JGI/DNA/Conth1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Conth1/download/Conth1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Conth1.gff3.gz 'https://genome.jgi.doe.gov/portal/Conth1/download/Conth1_FilteredModels1_deflines.gff3.gz' -b cookies
curl -o source/JGI/CDS/Conth1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Conth1/download/Conth1_GeneCatalog_CDS_20141003.fasta.gz' -b cookies
curl -o source/JGI/DNA/Cunech1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Cunech1/download/Cunech1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Cunech1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Cunech1/download/Cunech1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Cunech1.gff3.gz 'https://genome.jgi.doe.gov/portal/Cunech1/download/Cunech1_GeneCatalog_20170119.gff3.gz' -b cookies
curl -o source/JGI/CDS/Cunech1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Cunech1/download/Cunech1_GeneCatalog_CDS_20170119.fasta.gz' -b cookies
curl -o source/JGI/DNA/Dicele1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Dicele1/download/Dicele1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Dicele1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Dicele1/download/Dicele1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Dicele1.gff3.gz 'https://genome.jgi.doe.gov/portal/Dicele1/download/Dicele1_GeneCatalog_20170425.gff3.gz' -b cookies
curl -o source/JGI/CDS/Dicele1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Dicele1/download/Dicele1_GeneCatalog_CDS_20170425.fasta.gz' -b cookies
curl -o source/JGI/DNA/Dicrob1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Dicrob1/download/Dicrob1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Dicrob1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Dicrob1/download/Dicrob1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Dicrob1.gff3.gz 'https://genome.jgi.doe.gov/portal/Dicrob1/download/Dicrob1_GeneCatalog_20190615.gff3.gz' -b cookies
curl -o source/JGI/CDS/Dicrob1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Dicrob1/download/Dicrob1_GeneCatalog_CDS_20190615.fasta.gz' -b cookies
curl -o source/JGI/DNA/DimcrSC1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/DimcrSC1/download/DimcrSC1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/DimcrSC1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/DimcrSC1/download/DimcrSC1_MitochondrionScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/DimcrSC1.gff3.gz 'https://genome.jgi.doe.gov/portal/DimcrSC1/download/DimcrSC1_GeneCatalog_20151223.gff3.gz' -b cookies
curl -o source/JGI/CDS/DimcrSC1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/DimcrSC1/download/DimcrSC1_GeneCatalog_CDS_20151223.fasta.gz' -b cookies
curl -o source/JGI/DNA/Disorn1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Disorn1/download/Disorn1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Disorn1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Disorn1/download/Disorn1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Disorn1.gff3.gz 'https://genome.jgi.doe.gov/portal/Disorn1/download/Disorn1_GeneCatalog_20180714.gff3.gz' -b cookies
curl -o source/JGI/CDS/Disorn1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Disorn1/download/Disorn1_GeneCatalog_CDS_20180714.fasta.gz' -b cookies
curl -o source/JGI/DNA/Ellano1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Ellano1/download/Ellano1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Ellano1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Ellano1/download/Ellano1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Ellano1.gff3.gz 'https://genome.jgi.doe.gov/portal/Ellano1/download/Ellano1_GeneCatalog_20190325.gff3.gz' -b cookies
curl -o source/JGI/CDS/Ellano1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Ellano1/download/Ellano1_GeneCatalog_CDS_20190325.fasta.gz' -b cookies
curl -o source/JGI/DNA/Endsp1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Endsp1/download/Endsp1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Endsp1.gff3.gz 'https://genome.jgi.doe.gov/portal/Endsp1/download/Endsp1_GeneCatalog_20180904.gff3.gz' -b cookies
curl -o source/JGI/CDS/Endsp1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Endsp1/download/Endsp1_GeneCatalog_CDS_20180904.fasta.gz' -b cookies
curl -o source/JGI/DNA/Fenlin1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Fenlin1/download/Fenlin1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Fenlin1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Fenlin1/download/Fenlin1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Fenlin1.gff3.gz 'https://genome.jgi.doe.gov/portal/Fenlin1/download/Fenlin1_GeneCatalog_20170109.gff3.gz' -b cookies
curl -o source/JGI/CDS/Fenlin1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Fenlin1/download/Fenlin1_GeneCatalog_CDS_20170109.fasta.gz' -b cookies
curl -o source/JGI/DNA/Gigro1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Gigro1/download/Gigro1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Gigro1.gff3.gz 'https://genome.jgi.doe.gov/portal/Gigro1/download/Gigro1_GeneCatalog_20160405.gff3.gz' -b cookies
curl -o source/JGI/CDS/Gigro1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Gigro1/download/Gigro1_GeneCatalog_CDS_20160405.fasta.gz' -b cookies
curl -o source/JGI/DNA/Gilper1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Gilper1/download/Gilper1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Gilper1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Gilper1/download/Gilper1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Gilper1.gff3.gz 'https://genome.jgi.doe.gov/portal/Gilper1/download/Gilper1_GeneCatalog_20161121.gff3.gz' -b cookies
curl -o source/JGI/CDS/Gilper1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Gilper1/download/Gilper1_GeneCatalog_CDS_20161121.fasta.gz' -b cookies
curl -o source/JGI/DNA/Gonbut1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Gonbut1/download/Gonbut1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Gonbut1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Gonbut1/download/Gonbut1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Gonbut1.gff3.gz 'https://genome.jgi.doe.gov/portal/Gonbut1/download/Gonbut1_GeneCatalog_20160804.gff3.gz' -b cookies
curl -o source/JGI/CDS/Gonbut1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Gonbut1/download/Gonbut1_GeneCatalog_CDS_20160804.fasta.gz' -b cookies
curl -o source/JGI/DNA/Halrad1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Halrad1/download/Halrad1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Halrad1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Halrad1/download/Halrad1_MitochondrionScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Halrad1.gff3.gz 'https://genome.jgi.doe.gov/portal/Halrad1/download/Halrad1_GeneCatalog_20180330.gff3.gz' -b cookies
curl -o source/JGI/CDS/Halrad1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Halrad1/download/Halrad1_GeneCatalog_CDS_20180330.fasta.gz' -b cookies
curl -o source/JGI/DNA/Helpul1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Helpul1/download/Helpul1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Helpul1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Helpul1/download/Helpul1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Helpul1.gff3.gz 'https://genome.jgi.doe.gov/portal/Helpul1/download/Helpul1_GeneCatalog_20180613.gff3.gz' -b cookies
curl -o source/JGI/CDS/Helpul1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Helpul1/download/Helpul1_GeneCatalog_CDS_20180613.fasta.gz' -b cookies
curl -o source/JGI/DNA/Hesve2finisherSC.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Hesve2finisherSC/download/Hesve2finisherSC_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Hesve2finisherSC.gff3.gz 'https://genome.jgi.doe.gov/portal/Hesve2finisherSC/download/Hesve2finisherSC_GeneCatalog_2015_07_02_13_57_deflines.gff3.gz' -b cookies
curl -o source/JGI/CDS/Hesve2finisherSC.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Hesve2finisherSC/download/Hesve2finisherSC_GeneCatalog_CDS_20150707.fasta.gz' -b cookies
curl -o source/JGI/DNA/Jimfl_AD_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Jimfl_AD_1/download/Jimfl_AD_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Jimfl_AD_1.gff3.gz 'https://genome.jgi.doe.gov/portal/Jimfl_AD_1/download/Jimfl_AD_1_GeneCatalog_20180815.gff3.gz' -b cookies
curl -o source/JGI/CDS/Jimfl_AD_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Jimfl_AD_1/download/Jimfl_AD_1_GeneCatalog_CDS_20180815.fasta.gz' -b cookies
curl -o source/JGI/DNA/Jimfl_GMNB39_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Jimfl_GMNB39_1/download/Jimfl_GMNB39_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Jimfl_GMNB39_1.gff3.gz 'https://genome.jgi.doe.gov/portal/Jimfl_GMNB39_1/download/Jimfl_GMNB39_1_GeneCatalog_20180904.gff3.gz' -b cookies
curl -o source/JGI/CDS/Jimfl_GMNB39_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Jimfl_GMNB39_1/download/Jimfl_GMNB39_1_GeneCatalog_CDS_20180904.fasta.gz' -b cookies
curl -o source/JGI/DNA/Jimlac1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Jimlac1/download/Jimlac1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Jimlac1.gff3.gz 'https://genome.jgi.doe.gov/portal/Jimlac1/download/Jimlac1_GeneCatalog_20180910.gff3.gz' -b cookies
curl -o source/JGI/CDS/Jimlac1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Jimlac1/download/Jimlac1_GeneCatalog_CDS_20180910.fasta.gz' -b cookies
curl -o source/JGI/DNA/Kicala1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Kicala1/download/Kicala1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Kicala1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Kicala1/download/Kicala1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Kicala1.gff3.gz 'https://genome.jgi.doe.gov/portal/Kicala1/download/Kicala1_GeneCatalog_20170410.gff3.gz' -b cookies
curl -o source/JGI/CDS/Kicala1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Kicala1/download/Kicala1_GeneCatalog_CDS_20170410.fasta.gz' -b cookies
curl -o source/JGI/DNA/Liccor1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Liccor1/download/Liccor1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Liccor1.gff3.gz 'https://genome.jgi.doe.gov/portal/Liccor1/download/Liccor1_GeneCatalog_20160306.gff3.gz' -b cookies
curl -o source/JGI/CDS/Liccor1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Liccor1/download/Liccor1_GeneCatalog_CDS_20160306.fasta.gz' -b cookies
curl -o source/JGI/DNA/Lichy1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Lichy1/download/Lichy1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Lichy1.gff3.gz 'https://genome.jgi.doe.gov/portal/Lichy1/download/Lichy1.filtered_proteins.FilteredModels1.gff3.gz' -b cookies
curl -o source/JGI/CDS/Lichy1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Lichy1/download/Lichy1_GeneCatalog_CDS_20130506.fasta.gz' -b cookies
curl -o source/JGI/DNA/Linpe1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Linpe1/download/Linpe1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Linpe1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Linpe1/download/Linpe1_MitochondrianScaffold.fasta' -b cookies
curl -o source/JGI/GFF/Linpe1.gff3.gz 'https://genome.jgi.doe.gov/portal/Linpe1/download/Linpe1_GeneCatalog_2015_09_14_14_07_deflines.gff3.gz' -b cookies
curl -o source/JGI/CDS/Linpe1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Linpe1/download/Linpe1_GeneCatalog_CDS_20150915.fasta.gz' -b cookies
curl -o source/JGI/DNA/Lobtra1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Lobtra1/download/Lobtra1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Lobtra1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Lobtra1/download/Lobtra1_MitochondrionScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Lobtra1.gff3.gz 'https://genome.jgi.doe.gov/portal/Lobtra1/download/Lobtra1_GeneCatalog_20160303.gff3.gz' -b cookies
curl -o source/JGI/CDS/Lobtra1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Lobtra1/download/Lobtra1_GeneCatalog_CDS_20160303.fasta.gz' -b cookies
curl -o source/JGI/DNA/Marpt1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Marpt1/download/Marpt1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Marpt1.gff3.gz 'https://genome.jgi.doe.gov/portal/Marpt1/download/Marpt1_FilteredModels1_deflines.gff3.gz' -b cookies
curl -o source/JGI/CDS/Marpt1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Marpt1/download/Marpt1_GeneCatalog_CDS_20140919.fasta.gz' -b cookies
curl -o source/JGI/DNA/Morel2.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Morel2/download/Morel2_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Morel2.gff3.gz 'https://genome.jgi.doe.gov/portal/Morel2/download/Morel2_FilteredModels1_deflines.gff3.gz' -b cookies
curl -o source/JGI/CDS/Morel2.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Morel2/download/Morel2_GeneCatalog_CDS_20151120.fasta.gz' -b cookies
curl -o source/JGI/DNA/Morel_U14_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Morel_U14_1/download/Morel_U14_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Morel_U14_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Morel_U14_1/download/Morel_U14_1_MitochondrionScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Morel_U14_1.gff3.gz 'https://genome.jgi.doe.gov/portal/Morel_U14_1/download/Morel_U14_1_GeneCatalog_20180326.gff3.gz' -b cookies
curl -o source/JGI/CDS/Morel_U14_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Morel_U14_1/download/Morel_U14_1_GeneCatalog_CDS_20180326.fasta.gz' -b cookies
curl -o source/JGI/DNA/MoeNVP64_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/MoeNVP64_1/download/MoeNVP64_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/MoeNVP64_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/MoeNVP64_1/download/MoeNVP64_1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/MoeNVP64_1.gff3.gz 'https://genome.jgi.doe.gov/portal/MoeNVP64_1/download/MoeNVP64_1_GeneCatalog_20190403.gff3.gz' -b cookies
curl -o source/JGI/CDS/MoeNVP64_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/MoeNVP64_1/download/MoeNVP64_1_GeneCatalog_CDS_20190403.fasta.gz' -b cookies
curl -o source/JGI/DNA/Morhum1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Morhum1/download/Morhum1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Morhum1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Morhum1/download/Morhum1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Morhum1.gff3.gz 'https://genome.jgi.doe.gov/portal/Morhum1/download/Morhum1_GeneCatalog_20170607.gff3.gz' -b cookies
curl -o source/JGI/CDS/Morhum1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Morhum1/download/Morhum1_GeneCatalog_CDS_20170607.fasta.gz' -b cookies
curl -o source/JGI/DNA/Mormin1_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Mormin1_1/download/Mormin1_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Mormin1_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Mormin1_1/download/Mormin1_1_MitochondrionScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Mormin1_1.gff3.gz 'https://genome.jgi.doe.gov/portal/Mormin1_1/download/Mormin1_1_GeneCatalog_20180323.gff3.gz' -b cookies
curl -o source/JGI/CDS/Mormin1_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Mormin1_1/download/Mormin1_1_GeneCatalog_CDS_20180323.fasta.gz' -b cookies
curl -o source/JGI/DNA/Mormul1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Mormul1/download/Mormul1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Mormul1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Mormul1/download/Mormul1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Mormul1.gff3.gz 'https://genome.jgi.doe.gov/portal/Mormul1/download/Mormul1_GeneCatalog_20160906.gff3.gz' -b cookies
curl -o source/JGI/CDS/Mormul1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Mormul1/download/Mormul1_GeneCatalog_CDS_20160906.fasta.gz' -b cookies
curl -o source/JGI/DNA/MorAD185_1_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/MorAD185_1_1/download/MorAD185_1_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/MorAD185_1_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/MorAD185_1_1/download/MorAD185_1_1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/MorAD185_1_1.gff3.gz 'https://genome.jgi.doe.gov/portal/MorAD185_1_1/download/MorAD185_1_1_GeneCatalog_20190828.gff3.gz' -b cookies
curl -o source/JGI/CDS/MorAD185_1_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/MorAD185_1_1/download/MorAD185_1_1_GeneCatalog_CDS_20190828.fasta.gz' -b cookies
curl -o source/JGI/DNA/MorGBAus27b_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/MorGBAus27b_1/download/MorGBAus27b_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/MorGBAus27b_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/MorGBAus27b_1/download/MorGBAus27b_1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/MorGBAus27b_1.gff3.gz 'https://genome.jgi.doe.gov/portal/MorGBAus27b_1/download/MorGBAus27b_1_GeneCatalog_20170422.gff3.gz' -b cookies
curl -o source/JGI/CDS/MorGBAus27b_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/MorGBAus27b_1/download/MorGBAus27b_1_GeneCatalog_CDS_20170422.fasta.gz' -b cookies
curl -o source/JGI/DNA/Morve1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Morve1/download/Morve1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Morve1.gff3.gz 'https://genome.jgi.doe.gov/portal/Morve1/download/Morve1_GeneCatalog_20161024.gff3.gz' -b cookies
curl -o source/JGI/CDS/Morve1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Morve1/download/Morve1_GeneCatalog_CDS_20161024.fasta.gz' -b cookies
curl -o source/JGI/DNA/Mucci2.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Mucci2/download/Mucor_circinelloides_v2_scaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Mucci2.gff3.gz 'https://genome.jgi.doe.gov/portal/Mucci2/download/Mucci2.filtered_proteins.FilteredModels1.gff3.gz' -b cookies
curl -o source/JGI/CDS/Mucci2.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Mucci2/download/Mucor_circinelloides_v2_filtered_CDS.fasta.gz' -b cookies
curl -o source/JGI/DNA/Muccir1_3.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Muccir1_3/download/Muccir1_3_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Muccir1_3.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Muccir1_3/download/Muccir1_3_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Muccir1_3.gff3.gz 'https://genome.jgi.doe.gov/portal/Muccir1_3/download/Muccir1_3_GeneCatalog_20181206.gff3.gz' -b cookies
curl -o source/JGI/CDS/Muccir1_3.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Muccir1_3/download/Muccir1_3_GeneCatalog_CDS_20181206.fasta.gz' -b cookies
curl -o source/JGI/DNA/Kircor1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Kircor1/download/Kircor1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Kircor1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Kircor1/download/Kircor1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Kircor1.gff3.gz 'https://genome.jgi.doe.gov/portal/Kircor1/download/Kircor1_GeneCatalog_20160812.gff3.gz' -b cookies
curl -o source/JGI/CDS/Kircor1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Kircor1/download/Kircor1_GeneCatalog_CDS_20160812.fasta.gz' -b cookies
curl -o source/JGI/DNA/Zyghet1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Zyghet1/download/Zyghet1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Zyghet1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Zyghet1/download/Zyghet1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Zyghet1.gff3.gz 'https://genome.jgi.doe.gov/portal/Zyghet1/download/Zyghet1_GeneCatalog_20160427.gff3.gz' -b cookies
curl -o source/JGI/CDS/Zyghet1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Zyghet1/download/Zyghet1_GeneCatalog_CDS_20160427.fasta.gz' -b cookies
curl -o source/JGI/DNA/Mucmuc1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Mucmuc1/download/Mucmuc1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Mucmuc1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Mucmuc1/download/Mucmuc1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Mucmuc1.gff3.gz 'https://genome.jgi.doe.gov/portal/Mucmuc1/download/Mucmuc1_GeneCatalog_20181129.gff3.gz' -b cookies
curl -o source/JGI/CDS/Mucmuc1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Mucmuc1/download/Mucmuc1_GeneCatalog_CDS_20181129.fasta.gz' -b cookies
curl -o source/JGI/DNA/Mycafr1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Mycafr1/download/Mycafr1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Mycafr1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Mycafr1/download/Mycafr1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Mycafr1.gff3.gz 'https://genome.jgi.doe.gov/portal/Mycafr1/download/Mycafr1_GeneCatalog_20160506.gff3.gz' -b cookies
curl -o source/JGI/CDS/Mycafr1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Mycafr1/download/Mycafr1_GeneCatalog_CDS_20160506.fasta.gz' -b cookies
curl -o source/JGI/DNA/Parpar1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Parpar1/download/Parpar1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Parpar1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Parpar1/download/Parpar1_MitochondrionScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Parpar1.gff3.gz 'https://genome.jgi.doe.gov/portal/Parpar1/download/Parpar1_GeneCatalog_20160126.gff3.gz' -b cookies
curl -o source/JGI/CDS/Parpar1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Parpar1/download/Parpar1_GeneCatalog_CDS_20160126.fasta.gz' -b cookies
curl -o source/JGI/DNA/Phaart1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Phaart1/download/Phaart1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Phaart1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Phaart1/download/Phaart1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Phaart1.gff3.gz 'https://genome.jgi.doe.gov/portal/Phaart1/download/Phaart1_GeneCatalog_20160822.gff3.gz' -b cookies
curl -o source/JGI/CDS/Phaart1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Phaart1/download/Phaart1_GeneCatalog_CDS_20160822.fasta.gz' -b cookies
curl -o source/JGI/DNA/Phybl2.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Phybl2/download/Phycomyces_blakesleeanus_v2_scaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Phybl2.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Phybl2/download/Phycomyces_blakesleeanus_v2_mitochondrial_scaffold.fasta.gz' -b cookies
curl -o source/JGI/GFF/Phybl2.gff3.gz 'https://genome.jgi.doe.gov/portal/Phybl2/download/Phybl2.filtered_proteins.FilteredModels3.gff3.gz' -b cookies
curl -o source/JGI/CDS/Phybl2.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Phybl2/download/Phycomyces_blakesleeanus_v2_filtered_CDS.fasta.gz' -b cookies
curl -o source/JGI/DNA/Phybla1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Phybla1/download/Phybla1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Phybla1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Phybla1/download/Phybla1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Phybla1.gff3.gz 'https://genome.jgi.doe.gov/portal/Phybla1/download/Phybla1_GeneCatalog_20190111.gff3.gz' -b cookies
curl -o source/JGI/CDS/Phybla1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Phybla1/download/Phybla1_GeneCatalog_CDS_20190111.fasta.gz' -b cookies
curl -o source/JGI/DNA/PhyblU21_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/PhyblU21_1/download/PhyblU21_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/PhyblU21_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/PhyblU21_1/download/PhyblU21_1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/PhyblU21_1.gff3.gz 'https://genome.jgi.doe.gov/portal/PhyblU21_1/download/PhyblU21_1_GeneCatalog_20190528.gff3.gz' -b cookies
curl -o source/JGI/CDS/PhyblU21_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/PhyblU21_1/download/PhyblU21_1_GeneCatalog_CDS_20190528.fasta.gz' -b cookies
curl -o source/JGI/DNA/PnitS607_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/PnitS607_1/download/PnitS607_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/PnitS607_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/PnitS607_1/download/PnitS607_1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/PnitS607_1.gff3.gz 'https://genome.jgi.doe.gov/portal/PnitS607_1/download/PnitS607_1_GeneCatalog_20170410.gff3.gz' -b cookies
curl -o source/JGI/CDS/PnitS607_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/PnitS607_1/download/PnitS607_1_GeneCatalog_CDS_20170410.fasta.gz' -b cookies
curl -o source/JGI/DNA/PnitS608_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/PnitS608_1/download/PnitS608_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/PnitS608_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/PnitS608_1/download/PnitS608_1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/PnitS608_1.gff3.gz 'https://genome.jgi.doe.gov/portal/PnitS608_1/download/PnitS608_1_GeneCatalog_20170410.gff3.gz' -b cookies
curl -o source/JGI/CDS/PnitS608_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/PnitS608_1/download/PnitS608_1_GeneCatalog_CDS_20170410.fasta.gz' -b cookies
curl -o source/JGI/DNA/PnitS609_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/PnitS609_1/download/PnitS609_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/PnitS609_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/PnitS609_1/download/PnitS609_1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/PnitS609_1.gff3.gz 'https://genome.jgi.doe.gov/portal/PnitS609_1/download/PnitS609_1_GeneCatalog_20170410.gff3.gz' -b cookies
curl -o source/JGI/CDS/PnitS609_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/PnitS609_1/download/PnitS609_1_GeneCatalog_CDS_20170410.fasta.gz' -b cookies
curl -o source/JGI/DNA/Pilano1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Pilano1/download/Pilano1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Pilano1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Pilano1/download/Pilano1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Pilano1.gff3.gz 'https://genome.jgi.doe.gov/portal/Pilano1/download/Pilano1_GeneCatalog_20161117.gff3.gz' -b cookies
curl -o source/JGI/CDS/Pilano1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Pilano1/download/Pilano1_GeneCatalog_CDS_20161117.fasta.gz' -b cookies
curl -o source/JGI/DNA/Pilumb1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Pilumb1/download/Pilumb1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Pilumb1.gff3.gz 'https://genome.jgi.doe.gov/portal/Pilumb1/download/Pilumb1_GeneCatalog_20170307.gff3.gz' -b cookies
curl -o source/JGI/CDS/Pilumb1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Pilumb1/download/Pilumb1_GeneCatalog_CDS_20170307.fasta.gz' -b cookies
curl -o source/JGI/DNA/Pipcy3_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Pipcy3_1/download/Pipcy3_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Pipcy3_1.gff3.gz 'https://genome.jgi.doe.gov/portal/Pipcy3_1/download/Pipcy3_1_GeneCatalog_20160615.gff3.gz' -b cookies
curl -o source/JGI/CDS/Pipcy3_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Pipcy3_1/download/Pipcy3_1_GeneCatalog_CDS_20160615.fasta.gz' -b cookies
curl -o source/JGI/DNA/Pipcy2.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Pipcy2/download/Pipcy2_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Pipcy2.gff3.gz 'https://genome.jgi.doe.gov/portal/Pipcy2/download/Pipcy2.filtered_proteins.FilteredModels1.gff3.gz' -b cookies
curl -o source/JGI/CDS/Pipcy2.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Pipcy2/download/Pipcy2_GeneCatalog_CDS_20130828.fasta.gz' -b cookies
curl -o source/JGI/DNA/Radspe1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Radspe1/download/Radspe1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Radspe1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Radspe1/download/Radspe1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Radspe1.gff3.gz 'https://genome.jgi.doe.gov/portal/Radspe1/download/Radspe1_GeneCatalog_20161011.gff3.gz' -b cookies
curl -o source/JGI/CDS/Radspe1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Radspe1/download/Radspe1_GeneCatalog_CDS_20161011.fasta.gz' -b cookies
curl -o source/JGI/DNA/Rambr1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Rambr1/download/Rambr1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Rambr1.gff3.gz 'https://genome.jgi.doe.gov/portal/Rambr1/download/Rambr1_FilteredModels1_deflines.gff3.gz' -b cookies
curl -o source/JGI/CDS/Rambr1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Rambr1/download/Rambr1_GeneCatalog_CDS_20140929.fasta.gz' -b cookies
curl -o source/JGI/DNA/Rhice1_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhice1_1/download/Rhice1_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Rhice1_1.gff3.gz 'https://genome.jgi.doe.gov/portal/Rhice1_1/download/Rhice1_1_GeneCatalog_20160727.gff3.gz' -b cookies
curl -o source/JGI/CDS/Rhice1_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhice1_1/download/Rhice1_1_GeneCatalog_CDS_20160727.fasta.gz' -b cookies
curl -o source/JGI/DNA/Rhidi1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhidi1/download/Rhidi1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Rhidi1.gff3.gz 'https://genome.jgi.doe.gov/portal/Rhidi1/download/Rhidi1_GeneCatalog_20160421.gff3.gz' -b cookies
curl -o source/JGI/CDS/Rhidi1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhidi1/download/Rhidi1_GeneCatalog_CDS_20160421.fasta.gz' -b cookies
curl -o source/JGI/DNA/RhiirA1_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/RhiirA1_1/download/RhiirA1_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/RhiirA1_1.gff3.gz 'https://genome.jgi.doe.gov/portal/RhiirA1_1/download/RhiirA1_1_GeneCatalog_genes_20150518.gff.gz' -b cookies
curl -o source/JGI/CDS/RhiirA1_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/RhiirA1_1/download/RhiirA1_1_GeneCatalog_CDS_20150518.fasta.gz' -b cookies
curl -o source/JGI/DNA/RhiirA4.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/RhiirA4/download/RhiirA4_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/RhiirA4.gff3.gz 'https://genome.jgi.doe.gov/portal/RhiirA4/download/RhiirA4_GeneCatalog_genes_20150618.gff.gz' -b cookies
curl -o source/JGI/CDS/RhiirA4.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/RhiirA4/download/RhiirA4_GeneCatalog_CDS_20150618.fasta.gz' -b cookies
curl -o source/JGI/DNA/RhiirA5.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/RhiirA5/download/RhiirA5_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/RhiirA5.gff3.gz 'https://genome.jgi.doe.gov/portal/RhiirA5/download/RhiirA5_GeneCatalog_genes_20150706.gff.gz' -b cookies
curl -o source/JGI/CDS/RhiirA5.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/RhiirA5/download/RhiirA5_GeneCatalog_CDS_20150706.fasta.gz' -b cookies
curl -o source/JGI/DNA/RhiirB3.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/RhiirB3/download/RhiirB3_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/RhiirB3.gff3.gz 'https://genome.jgi.doe.gov/portal/RhiirB3/download/RhiirB3_GeneCatalog_genes_20150616.gff.gz' -b cookies
curl -o source/JGI/CDS/RhiirB3.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/RhiirB3/download/RhiirB3_GeneCatalog_CDS_20150616.fasta.gz' -b cookies
curl -o source/JGI/DNA/RhiirC2.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/RhiirC2/download/RhiirC2_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/RhiirC2.gff3.gz 'https://genome.jgi.doe.gov/portal/RhiirC2/download/RhiirC2_GeneCatalog_genes_20150810.gff.gz' -b cookies
curl -o source/JGI/CDS/RhiirC2.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/RhiirC2/download/RhiirC2_GeneCatalog_CDS_20150810.fasta.gz' -b cookies
curl -o source/JGI/DNA/Gloin1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Gloin1/download/Gloin1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Gloin1.gff3.gz 'https://genome.jgi.doe.gov/portal/Gloin1/download/Gloin1.filtered_proteins.FilteredModels1.gff3.gz' -b cookies
curl -o source/JGI/CDS/Gloin1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Gloin1/download/Gloin1_GeneCatalog_CDS_20120510.fasta.gz' -b cookies
curl -o source/JGI/DNA/Rhiir2_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhiir2_1/download/Rhiir2_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Rhiir2_1.gff3.gz 'https://genome.jgi.doe.gov/portal/Rhiir2_1/download/Rhiir2_1_GeneCatalog_20160502.gff3.gz' -b cookies
curl -o source/JGI/CDS/Rhiir2_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhiir2_1/download/Rhiir2_1_GeneCatalog_CDS_20160502.fasta.gz' -b cookies
curl -o source/JGI/DNA/Rhior3.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhior3/download/Rhior3_scaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Rhior3.gff3.gz 'https://genome.jgi.doe.gov/portal/Rhior3/download/Rhior3.filtered_proteins.BroadGene.gff3.gz' -b cookies
curl -o source/JGI/DNA/Rhimi_ATCC11559_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhimi_ATCC11559_1/download/Rhimi_ATCC11559_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Rhimi_ATCC11559_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhimi_ATCC11559_1/download/Rhimi_ATCC11559_1_MitochondrionScaffolds.fasta' -b cookies
curl -o source/JGI/GFF/Rhimi_ATCC11559_1.gff3.gz 'https://genome.jgi.doe.gov/portal/Rhimi_ATCC11559_1/download/Rhimi_ATCC11559_1_FilteredModels1_deflines.gff3.gz' -b cookies
curl -o source/JGI/CDS/Rhimi_ATCC11559_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhimi_ATCC11559_1/download/Rhimi_ATCC11559_1_GeneCatalog_CDS_20150408.fasta.gz' -b cookies
curl -o source/JGI/DNA/Rhich1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhich1/download/Rhich1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Rhich1.gff3.gz 'https://genome.jgi.doe.gov/portal/Rhich1/download/Rhich1.filtered_proteins.ExternalModels.gff3.gz' -b cookies
curl -o source/JGI/CDS/Rhich1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhich1/download/Rhich1_GeneCatalog_CDS_20131210.fasta.gz' -b cookies
curl -o source/JGI/DNA/Rhimi1_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhimi1_1/download/Rhimi1_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Rhimi1_1.gff3.gz 'https://genome.jgi.doe.gov/portal/Rhimi1_1/download/Rhimi1_1.filtered_proteins.FilteredModels2.gff3.gz' -b cookies
curl -o source/JGI/CDS/Rhimi1_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhimi1_1/download/Rhimi1_1_GeneCatalog_CDS_20130624.fasta.gz' -b cookies
curl -o source/JGI/DNA/Rhimi_ATCC52814_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhimi_ATCC52814_1/download/Rhimi_ATCC52814_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Rhimi_ATCC52814_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhimi_ATCC52814_1/download/Rhimi_ATCC52814_1_MitochondrionScaffolds.fasta' -b cookies
curl -o source/JGI/GFF/Rhimi_ATCC52814_1.gff3.gz 'https://genome.jgi.doe.gov/portal/Rhimi_ATCC52814_1/download/Rhimi_ATCC52814_1_FilteredModels1_deflines.gff3.gz' -b cookies
curl -o source/JGI/CDS/Rhimi_ATCC52814_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Rhimi_ATCC52814_1/download/Rhimi_ATCC52814_1_GeneCatalog_CDS_20150309.fasta.gz' -b cookies
curl -o source/JGI/DNA/Sakvas1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Sakvas1/download/Sakvas1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Sakvas1.gff3.gz 'https://genome.jgi.doe.gov/portal/Sakvas1/download/Sakvas1_GeneCatalog_20160730.gff3.gz' -b cookies
curl -o source/JGI/CDS/Sakvas1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Sakvas1/download/Sakvas1_GeneCatalog_CDS_20160730.fasta.gz' -b cookies
curl -o source/JGI/DNA/SmicuMNP_2.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/SmicuMNP_2/download/SmicuMNP_2_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/SmicuMNP_2.gff3.gz 'https://genome.jgi.doe.gov/portal/SmicuMNP_2/download/SmicuMNP_2_GeneCatalog_20170807.gff3.gz' -b cookies
curl -o source/JGI/CDS/SmicuMNP_2.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/SmicuMNP_2/download/SmicuMNP_2_GeneCatalog_CDS_20170807.fasta.gz' -b cookies
curl -o source/JGI/DNA/SmiculW2_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/SmiculW2_1/download/SmiculW2_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/SmiculW2_1.gff3.gz 'https://genome.jgi.doe.gov/portal/SmiculW2_1/download/SmiculW2_1_GeneCatalog_20170804.gff3.gz' -b cookies
curl -o source/JGI/CDS/SmiculW2_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/SmiculW2_1/download/SmiculW2_1_GeneCatalog_CDS_20170804.fasta.gz' -b cookies
curl -o source/JGI/DNA/Smimuc2.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Smimuc2/download/Smimuc2_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Smimuc2.gff3.gz 'https://genome.jgi.doe.gov/portal/Smimuc2/download/Smimuc2_GeneCatalog_20170808.gff3.gz' -b cookies
curl -o source/JGI/CDS/Smimuc2.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Smimuc2/download/Smimuc2_GeneCatalog_CDS_20170808.fasta.gz' -b cookies
curl -o source/JGI/DNA/Spifus1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Spifus1/download/Spifus1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Spifus1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Spifus1/download/Spifus1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Spifus1.gff3.gz 'https://genome.jgi.doe.gov/portal/Spifus1/download/Spifus1_GeneCatalog_20161021.gff3.gz' -b cookies
curl -o source/JGI/CDS/Spifus1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Spifus1/download/Spifus1_GeneCatalog_CDS_20161021.fasta.gz' -b cookies
curl -o source/JGI/DNA/Spoumb1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Spoumb1/download/Spoumb1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Spoumb1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Spoumb1/download/Spoumb1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Spoumb1.gff3.gz 'https://genome.jgi.doe.gov/portal/Spoumb1/download/Spoumb1_GeneCatalog_20170626.gff3.gz' -b cookies
curl -o source/JGI/CDS/Spoumb1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Spoumb1/download/Spoumb1_GeneCatalog_CDS_20170626.fasta.gz' -b cookies
curl -o source/JGI/DNA/Synrac1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Synrac1/download/Synrac1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Synrac1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Synrac1/download/Synrac1_MitochondrionScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Synrac1.gff3.gz 'https://genome.jgi.doe.gov/portal/Synrac1/download/Synrac1_GeneCatalog_20160125.gff3.gz' -b cookies
curl -o source/JGI/CDS/Synrac1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Synrac1/download/Synrac1_GeneCatalog_CDS_20160125.fasta.gz' -b cookies
curl -o source/JGI/DNA/Synfus1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Synfus1/download/Synfus1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Synfus1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Synfus1/download/Synfus1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Synfus1.gff3.gz 'https://genome.jgi.doe.gov/portal/Synfus1/download/Synfus1_GeneCatalog_20170105.gff3.gz' -b cookies
curl -o source/JGI/CDS/Synfus1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Synfus1/download/Synfus1_GeneCatalog_CDS_20170105.fasta.gz' -b cookies
curl -o source/JGI/DNA/Synplu1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Synplu1/download/Synplu1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Synplu1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Synplu1/download/Synplu1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Synplu1.gff3.gz 'https://genome.jgi.doe.gov/portal/Synplu1/download/Synplu1_primary_alleles_20160908.gff3.gz' -b cookies
curl -o source/JGI/CDS/Synplu1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Synplu1/download/Synplu1_primary_alleles_CDS_20160908.fasta.gz' -b cookies
curl -o source/JGI/DNA/Synps1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Synps1/download/Synps1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Synps1.gff3.gz 'https://genome.jgi.doe.gov/portal/Synps1/download/Synps1_GeneCatalog_20160128.gff3.gz' -b cookies
curl -o source/JGI/CDS/Synps1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Synps1/download/Synps1_GeneCatalog_CDS_20160128.fasta.gz' -b cookies
curl -o source/JGI/DNA/Thaele1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Thaele1/download/Thaele1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Thaele1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Thaele1/download/Thaele1_MitochondrionScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Thaele1.gff3.gz 'https://genome.jgi.doe.gov/portal/Thaele1/download/Thaele1_GeneCatalog_20160208.gff3.gz' -b cookies
curl -o source/JGI/CDS/Thaele1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Thaele1/download/Thaele1_GeneCatalog_CDS_20160208.fasta.gz' -b cookies
curl -o source/JGI/DNA/Thasp1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Thasp1/download/Thasp1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Thasp1.gff3.gz 'https://genome.jgi.doe.gov/portal/Thasp1/download/Thasp1_GeneCatalog_20160203.gff3.gz' -b cookies
curl -o source/JGI/CDS/Thasp1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Thasp1/download/Thasp1_GeneCatalog_CDS_20160203.fasta.gz' -b cookies
curl -o source/JGI/DNA/Umbisa1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Umbisa1/download/Umbisa1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Umbisa1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Umbisa1/download/Umbisa1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Umbisa1.gff3.gz 'https://genome.jgi.doe.gov/portal/Umbisa1/download/Umbisa1_GeneCatalog_20171025.gff3.gz' -b cookies
curl -o source/JGI/CDS/Umbisa1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Umbisa1/download/Umbisa1_GeneCatalog_CDS_20171025.fasta.gz' -b cookies
curl -o source/JGI/DNA/Umbra1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Umbra1/download/Umbra1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Umbra1.gff3.gz 'https://genome.jgi.doe.gov/portal/Umbra1/download/Umbra1.filtered_proteins.FilteredModels1.gff3.gz' -b cookies
curl -o source/JGI/CDS/Umbra1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Umbra1/download/Umbra1_GeneCatalog_CDS_20121109.fasta.gz' -b cookies
curl -o source/JGI/DNA/Umbelo1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Umbelo1/download/Umbelo1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Umbelo1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Umbelo1/download/Umbelo1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Umbelo1.gff3.gz 'https://genome.jgi.doe.gov/portal/Umbelo1/download/Umbelo1_GeneCatalog_20190614.gff3.gz' -b cookies
curl -o source/JGI/CDS/Umbelo1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Umbelo1/download/Umbelo1_GeneCatalog_CDS_20190614.fasta.gz' -b cookies
curl -o source/JGI/DNA/Piptie1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Piptie1/download/Piptie1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Piptie1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Piptie1/download/Piptie1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Piptie1.gff3.gz 'https://genome.jgi.doe.gov/portal/Piptie1/download/Piptie1_GeneCatalog_20180621.gff3.gz' -b cookies
curl -o source/JGI/CDS/Piptie1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Piptie1/download/Piptie1_GeneCatalog_CDS_20180621.fasta.gz' -b cookies
curl -o source/JGI/DNA/Umbsp_AD052_1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Umbsp_AD052_1/download/Umbsp_AD052_1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Umbsp_AD052_1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Umbsp_AD052_1/download/Umbsp_AD052_1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Umbsp_AD052_1.gff3.gz 'https://genome.jgi.doe.gov/portal/Umbsp_AD052_1/download/Umbsp_AD052_1_GeneCatalog_20160912.gff3.gz' -b cookies
curl -o source/JGI/CDS/Umbsp_AD052_1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Umbsp_AD052_1/download/Umbsp_AD052_1_GeneCatalog_CDS_20160912.fasta.gz' -b cookies
curl -o source/JGI/DNA/Zancul2.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Zancul2/download/Zancul2_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Zancul2.gff3.gz 'https://genome.jgi.doe.gov/portal/Zancul2/download/Zancul2_GeneCatalog_20170807.gff3.gz' -b cookies
curl -o source/JGI/CDS/Zancul2.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Zancul2/download/Zancul2_GeneCatalog_CDS_20170807.fasta.gz' -b cookies
curl -o source/JGI/DNA/Zoorad1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Zoorad1/download/Zoorad1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/MT/Zoorad1.mt.fasta.gz 'https://genome.jgi.doe.gov/portal/Zoorad1/download/Zoorad1_MitoAssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Zoorad1.gff3.gz 'https://genome.jgi.doe.gov/portal/Zoorad1/download/Zoorad1_GeneCatalog_20180427.gff3.gz' -b cookies
curl -o source/JGI/CDS/Zoorad1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Zoorad1/download/Zoorad1_GeneCatalog_CDS_20180427.fasta.gz' -b cookies
curl -o source/JGI/DNA/Zycmex1.nt.fasta.gz 'https://genome.jgi.doe.gov/portal/Zycmex1/download/Zycmex1_AssemblyScaffolds.fasta.gz' -b cookies
curl -o source/JGI/GFF/Zycmex1.gff3.gz 'https://genome.jgi.doe.gov/portal/Zycmex1/download/Zycmex1_GeneCatalog_20160711.gff3.gz' -b cookies
curl -o source/JGI/CDS/Zycmex1.cds.fasta.gz 'https://genome.jgi.doe.gov/portal/Zycmex1/download/Zycmex1_GeneCatalog_CDS_20160711.fasta.gz' -b cookies
